### PR TITLE
win32 port

### PR DESCRIPTION
**Pull request by xantares**

### CODE REVIEW

**Comment by xantares** [comment]
This fixes various cmake stuff and code oddities.

It adds an install target, which install data, this required to pull the CMakeLists at the root level, hope you dont mind.

Note that the current git version does not run, here's the gdb trace, any clues ?

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000000000041bd79 in Resources::createTexture (this=<optimized out>, filename=<optimized out>) at /home/xantares/projects/glPortal/source/engine/Resources.cpp:207
#2  0x000000000041bb5d in Resources::loadTextures (this=0x4328cc Resources::inst()::instance) at /home/xantares/projects/glPortal/source/engine/Resources.cpp:31
#3  0x000000000040b5ad in Game::loadTextures (this=<optimized out>) at /home/xantares/projects/glPortal/source/Game.cpp:420
#4  0x0000000000408f5a in main (argc=<optimized out>, argv=<optimized out>) at /home/xantares/projects/glPortal/source/Main.cpp:23

**Comment by hhirsch** [comment]
This looks like the texture file can not be found.

**Comment by xantares** [comment]
Where to look ?
All the files mentioned in Resources.cpp are present in /data.
it tries data/textures/font.png which is present then crashes
xan.

**Comment by xantares** [comment]
Never mind, it works on another machine with both the HEAD and this branch.
Ready to merge!
xan.

**Comment by xantares** [comment]
Hi,

It now builds successfully for windows.
It seems to launch through wine, but I can only see the portal flares launched and the introduction text. I have no win32 machine and cannot test it.

The linux version does not run on my linux box. It crashes at Resources.cpp:210
  glGenerateMipmap(GL_TEXTURE_2D);
altough GL_SGIS_generate_mipmap extension is in the list of the supported GL extensions.
Maybe my nouveau driver is faulty ?

Anyway I uploaded a zip there if it works on your windows system:
http://dl.free.fr/vQ4Z0vPMM
xan.

**Comment by xantares** [comment]
It almost loads now ; I can see the right hand on a blank screen :]
I have a problem with the shaders compiling: 
ERROR: definition for "void main()" not found.
xan.

**Comment by hhirsch** [comment]
Nice. This is very exciting.

**Comment by faustdotmef** [comment]
i can test binaries at windows xp

**Comment by xantares** [comment]
Don't bother tests the first binaries ; they were missing a lot of stuff.
Please remove them henry, I'll re-upload them soon.
I'll try tonight to fix the shaders build.
xan.

**Comment by xantares** [comment]
Hi,
This time it works!
http://dl.free.fr/kWoAzDWzI

Can you check it still works on your linux side and merge this branch ?
xan.

**Comment by hhirsch** [comment]
I will upload it later today.

**Comment by hhirsch** [comment]
I added the binaries the day before yesterday, got this response from one of my testers:
"32-bit version is finally working! Thank you glPortal team."

**Comment by xantares** [comment]
Great! Care to merge ? 
Xan.

Date: Mon, 28 Apr 2014 08:21:18 -0700

**Comment by hhirsch** [comment]
Can you tell me your cmake version? Last time I checked these commits did not compile for my debian 7 machine. I have to finish up some work before I can look into this in detail.

**Comment by xantares** [comment]
It should work on wheezy now.
xan.

**Comment by hhirsch** [comment]
With cmake version 2.8.9 on Wheezy I get:
No cmake_minimum_required command is present.

Did you remove
cmake_minimum_required(VERSION 2.8)
for any particular reason?

**Comment by xantares** [comment]
No,

it is there, 1st line of root cmakelists:
cmake_minimum_required(VERSION 2.8)You're configuring from the wrong folder !

xan.

Date: Tue, 29 Apr 2014 15:29:30 -0700

**Comment by hhirsch** [comment]
I see, you have split the cmakelist. It now compiles and runs nicely. I will attend to reviewing and pulling the changes as soon as I am finished with the new map file parser.

**Comment by hhirsch** [comment]
Hello Xan,

Julian has pulled your changes to our team account
https://github.com/GlPortal/glPortal
As testing progresses and we are getting closer to a release candidate for 0.0.8 I will also pull the changes to my private repository which seems to be the one primarily in use by most developers.

Haven't had time to test the install targets yet.

Regards 
Henry

**Comment by xantares** [comment]
ok!

**Pull request merged**
